language: java

jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7

matrix:
  include:
    - addons:
        apt:
          packages:
            - openjdk-6-jdk
      jdk: openjdk6

after_success:
  - mvn clean test jacoco:report coveralls:report